### ISSUE TITLE
Add pidfile to ensure only one instance is running

### ISSUE THREAD

**Issue by ammongit** [strinking/statbot#22]
Be sure to use some platform-independent python functionality to accomplish this. Since different configuration files may describe different instances, it should be per-config.

**Comment by ammongit** [comment]
There could be a field within the configuration that tells where a pid file should be written, if any.

**Comment by raylu-stripe** [comment]
this is generally a thing your process manager (systemd/upstart/supervisor/circus/start-stop-daemon) should do, not the program itself

**Comment by ammongit** [comment]
Fair enough.
