### ISSUE TITLE
Crawling giving up early

### ISSUE THREAD

**Issue by ammongit** [strinking/statbot#25]
Striking has an issue where on his machine, statbot only parses `#memes` and `#general`, but only partially reading through the entire history before giving up and saying all channels have been exhausted.

**Comment by ammongit** [comment]
Closing due to age. If @robstolarz encounters this issue again, he can reopen or make a new issue.

**Comment by robstolarz** [comment]
I think it's worth noting this only happened when statbot had the wrong permissions. Which is not something worth fixing, really.
