### ISSUE TITLE
Read deployment data from environment

### ISSUE THREAD

**Issue by ammongit** [strinking/statbot#28]
Eventually all bots with standardize on reading certain details like the bot token from environment variables.

**Comment by ammongit** [comment]
@robstolarz @raylu Given our discussion, will we still be using configuration via the environment, or will we be keeping what we have now?

**Comment by raylu** [comment]
¯\\(°_o)/¯

**Comment by robstolarz** [comment]
I'll take my bike shed in blue thanks :) 

I think we can just pass them as arguments and leave a note as to why we do that. Argparse is great.

**Comment by ammongit** [comment]
Right now the only argument we really accept is `-d`, for enabling debug logging. I suppose we could have every config option overridable with a CL argument.

**Comment by robstolarz** [comment]
Ah, we don't need quite that much. Just parameters for the database and the token would be enough, I think.

(unless you'd really like to do that...)
